# Generated by Django 4.2.13 on 2025-12-26 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-date_hired']},
        ),
    ]
